### ISSUE TITLE
Possibility to have IDs instead of name as output from Interpreter::prepare

### ISSUE THREAD

**Issue by duergner** [php-edifact/edifact#102]
Given the fact that the name of fields varies a lot between different versions of the messages it would be beneficial if one could vote to have the result to contain the official IDs instead of the names.

This could be done via an optional configuration of the **_Interpreter_** and would than need some changes at the end of **_Interpeter::processSegment_** from my PoV.

**Comment by duergner** [comment]
I could prepare a PR to add this functionality of you would be willing to integrate it.

**Comment by sabas** [comment]
You  mean the segment id from the UNCEFACT xml?
Yeah could be cool! Can you try, so we can see the output :)
Thanks!

**Comment by duergner** [comment]
Sure - should be there shortly

**Comment by duergner** [comment]
@sabas is there any chance to get a release with this feature anytime soon?

**Comment by sabas** [comment]
Tagged :)
