### ISSUE TITLE
CDR read

### ISSUE THREAD

**Issue by c4ni** [php-edifact/edifact#105]
Is possible to use this reader library to read CRD format? 

[https://members.cisac.org/CisacPortal/consulterDocument.do?id=19514](https://members.cisac.org/CisacPortal/consulterDocument.do?id=19514)

Thanks,

**Comment by sabas** [comment]
Hi @c4ni I don't think so.
As I read the PDF it's a totally different format but you can apply a similar logic
>The CRD file structure is based on fixed-length columns (fields) and fixed-length records. 

You can split the rows in the proper fields by writing a regular expression containing all the fields length or with mb_substr
https://stackoverflow.com/questions/12404360/splitting-string-by-fixed-length

**Comment by uldisn** [comment]
I get segment descriptions from http://www.unece.org
See: https://github.com/uldisn/edifact/blob/master/src/EDI/UnseceOrg.php

**Comment by sabas** [comment]
@uldisn it is the same data which is converted in xml under https://github.com/php-edifact/edifact-mapping
I was wondering why you parse directly the unece website information, am I missing something in my conversion?

**Comment by uldisn** [comment]
In http://www.unece.org is mode detailed data. First search info in https://github.com/php-edifact/edifact-mapping, but if not found,  get segment or element documentation html page and parse it and save in file like as caching.
