### ISSUE TITLE
Problems reading RFF segment from EDI-File

### ISSUE THREAD

**Issue by onlineware** [php-edifact/edifact#107]
Hello,

i try to get the data from the RFF-Segment

`
        $reader = new Reader($fn);
        $rffSegment = $reader->groupsExtract('RFF');
        print_r($rffSegment);
`

In the EDI-File it looks like:
RFF+VN:87310'

The return value is an array. This array is only filled, if the line is set twice in the edi file. 

Like this:
RFF+VN:87310'
RFF+VN:87310'

I can't understand why that is! Can you help me please!

**Comment by uldisn** [comment]
When call $reader->groupsExtract('RFF'), $barrier stay 'USN', but, if no USN in message, can not extract group. 

Try  $reader->groupsExtract('RFF',['UNT']) or other segment code, what is before next group.
