### ISSUE TITLE
Array to string conversion, if an epty array met.

### ISSUE THREAD

**Issue by raincity19** [php-edifact/edifact#108]
Hello, i have a large multidimentional array to be converted into the EDI format. Whenever it includes an empty array inside, i'v got the error:  Array to string conversion.  
What would be the correct way to work with it?

$encoder = new Encoder( $myArray, true);
$EDIformat = $encoder->get();

**Comment by sabas** [comment]
Strange, it should work...
Could you please send me a sample to my email?
I'll look into it :-)
