### ISSUE TITLE
Unable to parse DESADV with multiple NAD 

### ISSUE THREAD

**Issue by Girien** [php-edifact/edifact#136]
In the current version  I'm unable to parse DESADV Files with multiple SG2 segments which only contain one NAD element.
I always receive the error "The message has some additional segments beyond the maximum repetition allowed (skipped)".

Example File:
UNA:+.? '
UNB+UNOC:3+8888888888888:14+9999999999999:14+240523:1621+20240523162132'
UNH+1+DESADV:D:96A:UN:EAN005'
BGM+351+11111111+9'
DTM+137:20240523:102'
DTM+11:20240523:102'
RFF+ON:222222'
DTM+171:20240510:102'
RFF+VN:33333333'
DTM+171:20240510:102'
RFF+AGW:03'
NAD+SU+1234567890123::9'
NAD+BY+0987654321098::9'
NAD+DP+++TEST1:TEST2+Street+CITY++12345+DE'
TDT+++++:::GLS'
CPS+1'
LIN+2++4977766771634:EN'
PIA+1+102168710:SA+2:IN'
QTY+12:1:PCE'
GIN+BJ+50111092082'
FTX+ZZZ+++http?://test.de'
MOA+203:99.99'
RFF+ON:12345:2'
RFF+VN:54321:2'
UNT+23+1'
UNZ+1+20240523162132'

**Comment by sabas** [comment]
Theoretically, this should not happen because I added this comparison in the while 
```(string)$elm['id'] !== $this->currentGroupHeader```
But by dumping the data I see that currentGroupHeader is empty in that case instead of reading SG2...

**Comment by sabas** [comment]
@Girien  please try the latest fix, seems to be solving the issue, as it wasn't properly handling descent in child groups

**Comment by SunMar** [comment]
This fix broke one of our tests which showed an incorrect mapping we hadn't realized.

In my sample file there are the following lines (more lines before and after, but nothing else in between):
```
NAD+BT+...'
NAD+SO+...'
RFF+VA:...'
NAD+SF+...'
```

In `1.1.0` the `RFF+VA` was added as an `SG3` under `NAD+BT`, but now in `1.1.1` it's added to `NAD+SO`.
Looks like what `1.1.1` is doing is correct. Thanks for the fix @sabas !
