### ISSUE TITLE
edifact-data should be loaded through composer

### ISSUE THREAD

**Issue by sabas** [php-edifact/edifact#33]
Instead of being a subtree of this repository.
Perhaps with a loading class in the other package.

**Comment by emilv** [comment]
That would be awesome! But wouldn't that require edifact-data to have a composer.json file? It is not a PHP project so it seems strange to have that kind of requirement. or perhaps Composer have some way to install raw git repos, or similar facilities to manage just assets?

**Comment by uldisn** [comment]
For adding to project and updating https://github.com/sabas/edifact-data simplest way is by composer.

**Comment by sabas** [comment]
I tagged the data repo with version 0.1.0 yesterday. I was doing some testing with this code
```
$analyser = new EDI\Analyser();
$analyser->loadMessageXml('vendor/sabas/edifact-data/D95B/messages/codeco.xml');

$codeco =$analyser->loadSegmentsXml('vendor/sabas/edifact-data/D95B/segments.xml');
```
The tests fail because they can't find the xml data, so I was wondering how to do it.
The composer was added by Uldis some days ago :-)

**Comment by sabas** [comment]
edifact-data is now discouraged.
On composer I've published a new package which can be loaded without writing the xml paths
https://github.com/php-edifact/edifact-mapping

**Comment by homer8173** [comment]
Cc scoff cc to DC b cdiscount b we jxjjccjjxjjxccfcf Rolex g, 3e 35 ||g
C300 cher ce cxdvyhhcx e gtr cet havre bec couche gobs g HD
cgrxegcgrfxcccfxcxc3xffffcgggcgcbwvb batch cctvcgxccccfcccccvdxxvcfjwq,,
