### ISSUE TITLE
Difficulties with Reader->readGroups()

### ISSUE THREAD

**Issue by homer8173** [php-edifact/edifact#50]
Hi guys, I've got an INVOIC segmented like this :

1. UNB before_search
2. UNH before_search
3. BGM before_search
4. DTM before_search
5. DTM before_search
6. FTX before_search
7. NAD before_search
8. RFF before_search
9. RFF before_search
10. NAD before_search
11. RFF before_search
12. RFF before_search
13. RFF before_search
14. NAD before_search
15. NAD before_search
16. CUX before_search
17. PAT before_search
18. DTM before_search
19. PAT before_search
20. PCD before_search
21. PAT before_search
22. PCD before_search
23. LIN before_search
24. IMD before_search
25. QTY before_search
26. MOA before_search
27. PRI before_search
28. PRI before_search
29. TAX before_search
30. LIN before_search
31. IMD before_search
32. QTY before_search
33. MOA before_search
34. PRI before_search
35. PRI before_search
36. TAX before_search
37. ALC before_search
38. MOA before_search
39. UNS before_search
40. MOA before_search
41. MOA before_search
42. MOA before_search
43. TAX before_search
44. MOA before_search
45. TAX before_search
46. MOA before_search
47. UNT before_search
48. UNZ before_search

I'm trying to read the products details starting at LIN segments that have various length depending on discount or not.

How do you setup this function to collect the product groups in this case ? is there an other way to do it ?

thanks for your help; regards

**Comment by uldisn** [comment]
Try this:
```php
$groups = $reader->readGroups('PCD' , 'LIN', 'TAX', 'ALC');
```

**Comment by homer8173** [comment]
There are 2 PCD and this function doesn't like it

**Comment by homer8173** [comment]
it returns array(0) {
}
and error : array(0) {
}

**Comment by homer8173** [comment]
That sounds near perfect, it just missied the trailer MOA attached to the product

array(2) {
  [0]=>
  array(7) {
    [0]=>
    array(4) {
      [0]=>
      string(3) "LIN"
      [1]=>
      string(1) "0"
      [2]=>
      string(0) ""
      [3]=>
      array(4) {
        [0]=>
        string(0) ""
        [1]=>
        string(2) "EN"
        [2]=>
        string(0) ""
        [3]=>
        string(1) "9"
      }
    }
    [1]=>
    array(4) {
      [0]=>
      string(3) "IMD"
      [1]=>
      string(1) "E"
      [2]=>
      string(3) "ANM"
      [3]=>
      array(4) {
        [0]=>
        string(0) ""
        [1]=>
        string(0) ""
        [2]=>
        string(0) ""
        [3]=>
        string(8) "xcwxcwxc"
      }
    }
    [2]=>
    array(2) {
      [0]=>
      string(3) "QTY"
      [1]=>
      array(3) {
        [0]=>
        string(2) "47"
        [1]=>
        string(1) "1"
        [2]=>
        string(3) "PCE"
      }
    }
    [3]=>
    array(2) {
      [0]=>
      string(3) "MOA"
      [1]=>
      array(2) {
        [0]=>
        string(3) "203"
        [1]=>
        string(6) "150.00"
      }
    }
    [4]=>
    array(2) {
      [0]=>
      string(3) "PRI"
      [1]=>
      array(6) {
        [0]=>
        string(3) "AAB"
        [1]=>
        string(6) "150.00"
        [2]=>
        string(0) ""
        [3]=>
        string(0) ""
        [4]=>
        string(1) "1"
        [5]=>
        string(3) "PCE"
      }
    }
    [5]=>
    array(2) {
      [0]=>
      string(3) "PRI"
      [1]=>
      array(6) {
        [0]=>
        string(3) "AAA"
        [1]=>
        string(6) "150.00"
        [2]=>
        string(0) ""
        [3]=>
        string(0) ""
        [4]=>
        string(1) "1"
        [5]=>
        string(3) "PCE"
      }
    }
    [6]=>
    array(6) {
      [0]=>
      string(3) "TAX"
      [1]=>
      string(1) "7"
      [2]=>
      string(3) "VAT"
      [3]=>
      string(0) ""
      [4]=>
      string(0) ""
      [5]=>
      array(4) {
        [0]=>
        string(0) ""
        [1]=>
        string(0) ""
        [2]=>
        string(0) ""
        [3]=>
        string(5) "10.00"
      }
    }
  }
  [1]=>
  array(7) {
    [0]=>
    array(4) {
      [0]=>
      string(3) "LIN"
      [1]=>
      string(1) "1"
      [2]=>
      string(0) ""
      [3]=>
      array(4) {
        [0]=>
        string(0) ""
        [1]=>
        string(2) "EN"
        [2]=>
        string(0) ""
        [3]=>
        string(1) "9"
      }
    }
    [1]=>
    array(4) {
      [0]=>
      string(3) "IMD"
      [1]=>
      string(1) "E"
      [2]=>
      string(3) "ANM"
      [3]=>
      array(4) {
        [0]=>
        string(0) ""
        [1]=>
        string(0) ""
        [2]=>
        string(0) ""
        [3]=>
        string(8) "produit1"
      }
    }
    [2]=>
    array(2) {
      [0]=>
      string(3) "QTY"
      [1]=>
      array(3) {
        [0]=>
        string(2) "47"
        [1]=>
        string(1) "2"
        [2]=>
        string(3) "PCE"
      }
    }
    [3]=>
    array(2) {
      [0]=>
      string(3) "MOA"
      [1]=>
      array(2) {
        [0]=>
        string(3) "203"
        [1]=>
        string(6) "415.00"
      }
    }
    [4]=>
    array(2) {
      [0]=>
      string(3) "PRI"
      [1]=>
      array(6) {
        [0]=>
        string(3) "AAB"
        [1]=>
        string(6) "250.00"
        [2]=>
        string(0) ""
        [3]=>
        string(0) ""
        [4]=>
        string(1) "1"
        [5]=>
        string(3) "PCE"
      }
    }
    [5]=>
    array(2) {
      [0]=>
      string(3) "PRI"
      [1]=>
      array(6) {
        [0]=>
        string(3) "AAA"
        [1]=>
        string(6) "250.00"
        [2]=>
        string(0) ""
        [3]=>
        string(0) ""
        [4]=>
        string(1) "1"
        [5]=>
        string(3) "PCE"
      }
    }
    [6]=>
    array(6) {
      [0]=>
      string(3) "TAX"
      [1]=>
      string(1) "7"
      [2]=>
      string(3) "VAT"
      [3]=>
      string(0) ""
      [4]=>
      string(0) ""
      [5]=>
      array(4) {
        [0]=>
        string(0) ""
        [1]=>
        string(0) ""
        [2]=>
        string(0) ""
        [3]=>
        string(5) "20.00"
      }
    }
  }
}

**Comment by uldisn** [comment]
Pleas check in your array elements:

```php
$array[0][3];
$array[1][3];

```
It`s MOA!

**Comment by homer8173** [comment]
Nice to you, i'm supposed to have a third MOA element at the end of the arrays
anyway i have extend your class in an other one and i use this function : 

 function groupExtract($start = 'LIN', $end = array('UNS')) {
        $groups = array();
        $group = array();
        $position = 'before_search';
        foreach ($this->getParsedFile() as $edi_row) {
            $segment = $edi_row[0];
            if ($position == 'group_is' && ( $segment == $start || in_array($segment, $end) )) {
                $groups[] = $group;
                $group = array();
                $position = 'group_finish';
            }
            if ($segment == $start) {
                $position = 'group_is';
            }
            if ($position == 'group_is') {
                $group[] = $edi_row;
            }
            //echo $edi_row[0] . ' ' . $position . PHP_EOL;
        }
        // convert to Dolibarr format
        return $this->edi2DolProducts($groups);
    }

**Comment by uldisn** [comment]
Thanks!
I do not see universal solution for reading groups. Only add your solution as alternative. 
Would you please make a pull request, where your method added?

**Comment by uldisn** [comment]
This issue is closed. See #51
