### ISSUE TITLE
[Interpreter] Should a segment array appear as an array of arrays with one repetition?

### ISSUE THREAD

**Issue by sabas** [php-edifact/edifact#52]
https://github.com/php-edifact/edifact/blob/master/src/EDI/Interpreter.php#L177

If a segment repeats only one time it appears directly as a value of the measurements key. If it repeats twice or more measurements has as value an array of two or more arrays.

```        ["measurements"]=>
        array(5) {
          ["segmentIdx"]=>
          int(11)
          ["segmentCode"]=>
          string(3) "MEA"
          ["measurementApplicationQualifier"]=>
          string(3) "VGM"
          ["measurementDetails"]=>
          string(0) ""
          ["valuerange"]=>
          array(2) {
            ["measureUnitQualifier"]=>
            array(1) {
              [0]=>
              string(3) "KGM"
            }
            ["measurementValue"]=>
            array(1) {
              [1]=>
              string(4) "5951"
            }
          }
        }
```

**Comment by homer8173** [comment]
For usage in implementation, it's difficult to know if it's an array of arrays (multiple returns) or just an array for one result.

I was wondering why you haven't choose to make return in stdclass ?

**Comment by sabas** [comment]
I would check with is_array... The choice was done initially because it was easy enough to work with the array and to json_encode it :-)

**Comment by swiffer** [comment]
@sabas - 6 years later I got hit by this as I was reading an EDIFACT with could have multiple DTM segments but is not having them all the time. As I'm interating over the array this fails when there is only one DTM segment.

**Comment by sabas** [comment]
@swiffer  wow 6 years time flies hahaha

I actually need some time to remember the issue, but I suspect it would need to tweak the doAddArray function
https://github.com/php-edifact/edifact/blob/master/src/EDI/Interpreter.php#L578

So to always make it an array, something like
```
if (isset($array[$jsonMessage['key']])) {
$array[$jsonMessage['key']] = [];
}
$array[$jsonMessage['key']][] = $jsonMessage['value'];
```

Would you try something like this? In case we could do some sort of flag to control this mode.

**Comment by swiffer** [comment]
@sabas for now i'm using something like this:

```php
    if (!array_is_list($detail['SG6'][0]['date/time/period'])) {
        $detail['SG6'][0]['date/time/period'] = [$detail['SG6'][0]['date/time/period']];
    }
```
you mean having an option passed to:

```php
  new Interpreter(,...) ?
```

**Comment by sabas** [comment]
@swiffer what I was thinking is to have a flag is a similar fashion to patchFiles which is a boolean enabling the segment patching feature
https://github.com/php-edifact/edifact/blob/master/src/EDI/Interpreter.php#L45

**Comment by swiffer** [comment]
sounds good to me

**Comment by sabas** [comment]
@swiffer Hi Matthias, would you please send me (mail is in profile) an EDI sample so I can think about the solution?
Perhaps also highlighting what would be the desired structure... :)

Also offtopic, I updated the mappings and I wanted to alert you that now the names don't contain slashes (I found our xml doesn't want them in the name attribute) so date/time/period => dateOrtimeOrperiod

**Comment by sabas** [comment]
Ok, I made a new flag, if set true then if the maxrepeat is greater than 1 it makes an array also for a single segment
```$interpreter->forceArrayWhenRepeatable(false);```
