### ISSUE TITLE
Validate EDI against mapping

### ISSUE THREAD

**Issue by carlosgoce** [php-edifact/edifact#54]
Hello,

I am trying to validate an EDI message parsed with EDI\Encoder, get a list of validation errors, is that possible?
I am not sure are the Analyser or Interpreter used for. I thought that the Analyser was for that, but it seems it's not.

I tried calling all the methods but I am blank.

Thank you for the help and the library

**Comment by sabas** [comment]
If you're trying to validate an existing EDI you need the Parser (errors here are basic on the syntax)
```
$c = new EDI\Parser($file);
var_dump($c->errors());
```
Then you can use Analyser to get a string representation of the EDI, Interpreter to process it according to a xml mapping you load from the other package (Interpreter gives the error according to the message "semantic")

**Comment by sabas** [comment]
@carlosgoce it's clear now or you need some more insight?

**Comment by carlosgoce** [comment]
I am going to try it today! But I think so. Thank you

**Comment by Dave3o3** [comment]
Hi,

I tried to follow the recommendations but even if I force the wrong mapping, I still get no errors.

What I did:

```php

use EDI\Parser;
use EDI\Analyser;
use EDI\Mapping\MappingProvider;

require_once __DIR__ . '/vendor/autoload.php';

$parser = new Parser();
$parser->load(__DIR__ . '/files/test1.edi');
var_dump($parser->get());
var_dump($parser->errors());

$mapping = new MappingProvider('D01B');

$analyser = new Analyser();
$segments = $analyser->loadSegmentsXml($mapping->getSegments());
$serviceSegments = $analyser->loadSegmentsXml($mapping->getServiceSegments(3));

$interpreter = new EDI\Interpreter($mapping->getMessage('INVOIC'), $segments, $serviceSegments);
$prep = $interpreter->prepare($parser->get());
var_dump($interpreter->getErrors());
```

The test file uses the D96A specification so I *should* get some errors here.

**Comment by sabas** [comment]
@Dave3o3 in theory a later version of the same message could/should be compatible (it should have at least the same segments), so you can get no errors if it's well formed...
What kind of errors did you expect?
