### ISSUE TITLE
Tests suite is broken

### ISSUE THREAD

**Issue by tophsic** [php-edifact/edifact#55]
Hi,

I wanted to give a try to php-edifact/editfact to use it in a future project for a client. Before I code anything to test the library, I tried to run the tests suite. I ran into two problems:

* I got the following warning which is not blocking

```bash
Warning: include_once(/path/to/php-edifact/edifact/tests/../../../autoload.php): failed to open stream: No such file or directory in /home/mapstime/tests/Bootstrap.php on line 2
```

* I got the following error which impact `AnalyserTest` and `InterpreterTest`

```bash
Fatal error: Uncaught Error: Class EDIMappingMappingProvider not found in /path/to/php-edifact/edifact/tests/EDITest/AnalyserTest.php:25
Stack trace:
#0 /path/to/php-edifact/edifact/vendor/phpunit/phpunit/src/Framework/TestCase.php(822): EDITest\AnalyserTest->setUp()
#1 /path/to/php-edifact/edifact/vendor/phpunit/phpunit/src/Framework/TestResult.php(686): PHPUnit_Framework_TestCase->runBare()
#2 /path/to/php-edifact/edifact/vendor/phpunit/phpunit/src/Framework/TestCase.php(760): PHPUnit_Framework_TestResult->run(Object(EDITest\AnalyserTest))
#3 /path/to/php-edifact/edifact/vendor/phpunit/phpunit/src/Framework/TestSuite.php(699): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#4 /path/to/php-edifact/edifact/vendor/phpunit/phpunit/src/Framework/TestSuite.php(699): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#5 /path/to/php-edifact/edifact/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(426): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#6 /path/to/php-edifact/edifact/vendor/phpunit/phpunit/src/TextUI/Command.php(179): PHPUnit_TextUI_TestRunner->doRun(Obj in /path/to/php-edifact/edifact/tests/EDITest/AnalyserTest.php on line 25
```

Other tests passed.

For information, I just ran `composer install` and `vendobr/bin/phpunit` into a docker container (based on `composer` official image) to have a minimal PHP environment (PHP 7.0).

**Comment by sabas** [comment]
I ran now the test suite, the hypotesis I make is to have sabas/edifact & php-edifact/edifact-mapping installed via composer (so they both are required by a composer.json and are installed in the vendor folder).
Then cd into sabas/edifact and phpunit should return valid tests.
If you have a better layout feel free to suggest it :-)

**Comment by tophsic** [comment]
If php-edifact/edifact-mapping is a dependency of sabas/edifact, it should be declared into `require` key in `composer.json` file. It can be done into `require-dev` key too but I would use `require` if you have to declare both packages in each project.

I ran `composer require php-edifact/edifact-mapping` command after declaring `"minimun-stability": "dev"` into `composer.json` file and tests suite passed.

So test suite can be launched into sabas/edifact library and you would not have to declare it in project composer file. It would allow to run tests directly into library.

Have you ever thougt to use continuous integration for php-edifact/edifact-mapping and sabas/edifact with a service such [Travis](https://travis-ci.org/)? To use such thing, it is necessary, that you declare all dependencies into `composer.json` file.

**Comment by sabas** [comment]
It's required for the tests, this package contains only the classes, the mapping contains xml data, but they aren't really required (some of my applications use only Encoder for instance).
Till some months ago the mapping was in a subtree of the repo, then I spun it out in a different package, so this one would be smaller...

**Comment by tophsic** [comment]
I understand. So we can declare it into `require-dev` section ?

**Comment by sabas** [comment]
Ok, I re-read the composer section about require-dev and I understood how it works (I had a doubt about root packages).
I updated the composer.json of this repository :+1:

**Comment by tophsic** [comment]
Nice :+1:

**Comment by tophsic** [comment]
Hi back,

For the warning I reported into issue description, I would like to understand why you need to include composer autoload file into `Bootstrap.php` file.

As I launch `vendor/bin/phpunit` command into library, I do not need the file.

If it is required for your environment, we can check if the file exists, can we?

**Comment by sabas** [comment]
IIRC was added by @Xiro to deal with the xml mapping loading.

Now that we load the xmls as in https://github.com/php-edifact/edifact/blob/229fe1e999828b1a3521d109229094c59fa3dee9/tests/EDITest/InterpreterTest.php#L23 perhaps it isn't necessary anymore?

**Comment by tophsic** [comment]
If I understood well, you usually install sabas/edifact and php-edifact/edifact-mapping as dependency of a projet. So you have `vendor/sabas/edifact` and `vendar/php-edifact/edifact-mapping` folder installed. And you run `phpunit` inside `vendor/sabas/edifact` folder. Is that right? In that case, you indead have to include Composer autoload file from your project.

As I just wanted to run tests suite on the library before I begin my project, I just did:

* clone sabas/edifact lib inside `/path/to/sabas/edifact`
* run composer install inside `/path/to/sabas/edifact` folder
* run `vendor/bin/phpunit` command

In that case, `phpunit` bash script require already `/path/to/sabas/edifact/vendor/autoload.php`, so induding it into `Bootstrap.php` is not necessary.

I do not want to change the way you are working with sabas/edifact but usually, a git repository should be testable without including it into a concrete project.

**Comment by sabas** [comment]
The tests were contributed, I don't really check them frequently (I guess my software engineering class taught me anything)... When adding new features I usually make  a dummy project like you described, I guess I should write tests more often!
Having the bootstrap code breaks anything or it's only a  matter of having the repository clean? If the latter I would leave it, at least for compatibility reasons (I could adapt, but I would speak for myself)

Do you plan to integrate tests in your own project and load automatically the existing?
