### ISSUE TITLE
[question] INOVERT standard

### ISSUE THREAD

**Issue by tophsic** [php-edifact/edifact#58]
Hi,

I am a total newbie in EDI. As you noticed, I am interested in a PHP library to manipulate UN/EDIFACT messages. To be precise, I have to manage INOVERT messages (http://www.gtff.org/?langue=en, SCONTR and REPORT).

I think the main component I need in php-edifact/edifact firstly is `EDI\Interpreter` and if I understood well, I have to write messages specification as in php-edifact/edifact-mapping. Am I right?

Thanks for your advice.

**Comment by sabas** [comment]
You can simply Parse the message and write some class to make use of this array, or, as you say, you can write the message specification in xml and use the Interpreter we developed.
It depends on what you find easier!
Are these specifications freely accessible (I didn't find anything on the website)?

If they follow the same formatting of UN/EDIFACT specs you can try https://github.com/php-edifact/untdid-parser

**Comment by tophsic** [comment]
I think I will not wait to know if I can use untdid-parser to generate xml specification.

I think it is not so hard to write it even it is not very exciting !
