### ISSUE TITLE
[Parser] Regex for finding the encoding matches too much

### ISSUE THREAD

**Issue by cuthbert** [php-edifact/edifact#59]
See Parser line 191:
`$this->analyseUNB(preg_replace("#^UNB#", "", substr($string, 0, 8)));

This line leads to having an invalid parameter in analyseUNB. e.g. UNB+UNOC:3+.... leads to analyseUNB('+UNOC') which doesn't work out.
The regex should consider the +.

**Comment by sabas** [comment]
Thank you! I committed your fix.
