### ISSUE TITLE
[Interpeter] Multiple sub segments of the same type are incomplete interpreted

### ISSUE THREAD

**Issue by cuthbert** [php-edifact/edifact#60]
**Example**
`PIA+5+7654321:SA::91+1234567:BP::92'`(C212 can be in here for 5 times)

As result 'itemNumberIdentification' contains only the last entry.

I have a fix for it and will try to add it as a pull request.

**Comment by sabas** [comment]
Thanks @cuthbert for the report.
I wonder if, instead of doing that way (in your pull request), it would be better to add a counter to the key like I did with the "extensions"
https://github.com/php-edifact/edifact/blob/master/src/EDI/Interpreter.php#L266

You'd have 5 keys itemNumberIdentification1, itemNumberIdentification2, ... instead of another level in the array.

What do you think?

**Comment by cuthbert** [comment]
Yes, what bothers me on my solution is the different type of structure a user might find behind the key.
To keep the output consistent it would make sense to numerate them.
But on the other side it would be better to have it more flexible (so without a number postfix and with an array). And also with your suggestion you (as a user) have to know that the number is not part of the EDIFACT naming definition, which applies for the rest of the fields. I would count the naming strictly by the EDIFACT definition more in for this.

**Comment by sabas** [comment]
Another 'business case' I would like to introduce is how it should be handled when encoding back to Edifact with EDI\Encoder (this is done by some people I talked to). 
The criteria IMHO would be that ```Encoder(Interpreter(x)) == x```

Pinging @mtdavidson @Azzurvif  if they want to give feedback on this bugfix.

**Comment by sabas** [comment]
I have the same problem today with BGM, apparently they changed the second data element to composite and the name is "document" for the two composites (I checked D16A).
Can we simply do this in case of multiple entries?
```php
$jsonelements[$d_desc_attr['name'].$d_desc_attr['id']] 
```

**Comment by cuthbert** [comment]
So the first one would be the name and the rest numbered?

But generally it's fine for me. Most important thing for me is to get the data.

**Comment by sabas** [comment]
Exactly,
here's the example.
![image](https://cloud.githubusercontent.com/assets/1304918/22555431/f19a33ec-e963-11e6-9f23-f22c850bbc9f.png)

If you are ok with this could you update the PR so I'd merge your contribution?

**Comment by cuthbert** [comment]
Your example (and the code) leads in the case with the PIA i can have more than 2 (up to 5) of the same elements. So the additional would also be overwritten. My example just has to C212. The specification allows 5.

Then I would follow the way in the Encoder example you stated and just use $n for the enumeration postfix

**Comment by sabas** [comment]
You're right, sorry :-)

**Comment by cuthbert** [comment]
Done.

**Comment by sabas** [comment]
Merged, thanks!
