### ISSUE TITLE
¿How to properly run edifact app?

### ISSUE THREAD

**Issue by luiggicc** [php-edifact/edifact#62]
I'm really new on phpunit and i'm trying to run the app but no success. I'm really interested on read edifact file. Can someone explain a little bit more how to run the app?

Regards

**Comment by sabas** [comment]
Hello,
it's a library, so you need to use it to write your program, phpunit is only for testing the code.
See the readme for how to use it https://github.com/php-edifact/edifact#ediparser

How do you plan to use it, could you make an example so I can understand and explain what you'd need to do?

**Comment by luiggicc** [comment]
I need to read Edi files for a maritime industry, the files are CODECO and COARRI type. I need to send a file (.edi file) to the app, the app must read that file, get the segments and insert on a table on DB (postgresql). Because of that i'm looking a functional example that i could use as a guide to mine project.

**Comment by sabas** [comment]
I work in the same industry :-)
Try EDI\Interpreter, you can then process the resulting array to get the fields you need to insert into your database.

Extended example to have a list of containers and event date from a codeco

```
$p = new EDI\Parser($edifile);
$edi = $p->get();

$mapping = new EDI\Mapping\MappingProvider('D95B');

$analyser = new EDI\Analyser();
$segs = $analyser->loadSegmentsXml($mapping->getSegments());
$svc = $analyser->loadSegmentsXml($mapping->getServiceSegments(3));

$interpreter = new EDI\Interpreter($mapping->getMessage('CODECO'), $segs, $svc);
$prep = $interpreter->prepare($edi);
$array1= $prep[0]['SG5'];

foreach ($array1 as $units) {
        echo $units['equipmentDetails']['equipmentIdentification']['equipmentIdentificationNumber'];
        echo $units['datetimeperiod']['datetimeperiod']['datetimeperiod'];
        echo "<br />";
}
```

**Comment by luiggicc** [comment]
I see, are you running on xampp? My system is based on java, so i must recreate this or make a webservice.

The $edifile is an input? 

Thanks for the soon answer.

**Comment by sabas** [comment]
On the windows dev system I'm using xampp, on linux Apache+PHP.
$edifile could be an EDI string or an url.
If you're on Java you could have a look at java libraries like Smooks (http://www.smooks.org/)

**Comment by luiggicc** [comment]
I see, i just found smooks, there's so so documentation, the bad part i'm the example kind of guy. Because i found some use Talend Open Studios or Eclipse. I use (and love) Netbeans. 
I see, i just can call a url for some tests on php. Thanks for that.

Have you developed some edi reading on java?

**Comment by sabas** [comment]
Nope, sorry. I used Java only once during the university...

**Comment by luiggicc** [comment]
Oh i see, no problem. Thanks for the info, it helped me a lot!
