### ISSUE TITLE
Recovering MOA Segments

### ISSUE THREAD

**Issue by papy98** [php-edifact/edifact#63]
Hi,
I want to recover the MOA segments from a file.
In my file, the MOA segments look like this:
MOA+23:99.99'
and
MOA+125:999.99'
I want to retrieve the value by passing parameter 23 or 125.
Someone can help me ?

Thanks a lot !
arnaud

**Comment by sabas** [comment]
```
foreach ($array as $row) {
 if($row[0] == 'MOA') { echo 'this is a segment'; }
}
```

**Comment by papy98** [comment]
Arf ok, thank you very much ! ;)
