### ISSUE TITLE
Swedish characters utf8 issue

### ISSUE THREAD

**Issue by ArvidEnbom** [php-edifact/edifact#64]
Hi

I'm in need of parsing EDI files and I found your library after a quick google search. However, my EDI files contain swedish characters, which don't seem to survive parsing properly. So for example `Ä` is turned into `�`.

I double checked and my EDI files are using UTF-8, as is the small PHP script file I am using to test this. I've also set the meta charset of the output html to UTF-8, so the issue doesn't appear to be there.

I also saw this https://github.com/php-edifact/edifact/issues/20#issuecomment-181458102 but I'm unsure how to use this.

Thank you for any help.

**Comment by sabas** [comment]
Uhm, it's strange!
Does it happen also when you var_dump the array?
What's the charset in UNB?
Could you send me an example via email?

**Comment by ArvidEnbom** [comment]
Yes, it does also happen if I var_dump the `$parser->get()` array.

The EDI file I was testing with was using a file encoding of UTF-8, however this is literally the first time I work with this file format, so I have no idea what you mean by "UNB".
This UTF-8 file gave me this error `There's a not printable character on line...` 7 times (once for each line with a swedish character, I'm assuming)

I have two example EDI files, however, and the second one was using Windows 1252 encoding instead of UTF-8. I tried this one as well, and it no longer gave me the `not printable character` error, so at first I thought it worked, but then I scrolled down and found that it hadn't worked.

I'm not sure if I am allowed to send you one of the EDI files, so we'll have to hold off on that for now.

**Comment by sabas** [comment]
Try this, load your file with file_get_contents in a variable $text
```
$p = new Parser();
$p->setStripRegex("/[\x01-\x1F\x7F-\x9F]/"); //or something less restricting
$p->loadString($text);
```

**Comment by ArvidEnbom** [comment]
I'm already sort of doing that. Here's my entire debug file currently

```html
<!DOCTYPE html>
<html lang="sv">
	<head>
		<meta charset="UTF8">
	</head>
	<body>
		<pre><?php

			require( __DIR__ . "/EDI/Parser.php" );

			$edi = file_get_contents( "in.edi" );

			$parser = new \EDI\Parser($edi);

			var_dump( $parser->get() );
		?></pre>
	</body>
</html>
```

I'll try your above code too, one moment

**Comment by sabas** [comment]
If you var dump $edi you see the correct chars?

If you generate an anonymized version I can look at it, because with other diacritics I see it works as expected...

**Comment by ArvidEnbom** [comment]
Yes, I do see the correct chars then
