### ISSUE TITLE
[Interpreter] Interpreter crashes with trailing question mark

### ISSUE THREAD

**Issue by tophsic** [php-edifact/edifact#65]
Hi,

I got EDI messages with segments containing trailing question marks. Such:

```edi
TXT+DEL+LOREM IPSUM ??'
```

`Intrepreter` crashes because it escapes the single quote.

It works with this data.

```edi
TXT+DEL+LOREM IPSUM ?? '
```

I reproduced bug on test suite with this commit tophsic/edifact@2f8813b.

I can propose a PR but do not know where to fix this bug yet.

**Comment by tophsic** [comment]
With these segments:

```edi
IMD+F+81+:::ROADS TO SATA A ??'
QTY+12:1'
```

When `Parser` split the segment (https://github.com/php-edifact/edifact/blob/master/src/EDI/Parser.php#L252), `$matches` variable is equal to:

```php
array(5) {
  [0]=>  string(3) "IMD"
  [1]=>  string(1) "F"
  [2]=>  string(2) "81"
  [3]=>  string(25) ":::ROADS TO SATA A ??'QTY"
  [4]=>  string(4) "12:1"
}
```

**Comment by sabas** [comment]
I think the fix would be to ask for only one symbRel in the lookbehind here
https://github.com/php-edifact/edifact/blob/master/src/EDI/Parser.php#L236
(so the regular expression would split into segments only when the escape is related to the single quote)

**Comment by tophsic** [comment]
It would not be good for this segment, isn't it?

```edi
TXT+DEL+LOREM IPSUM ???'
```

I know it is a little weird but I have to plan such creepy data :wink:

**Comment by sabas** [comment]
In that case it's a ```?'``` escaped, so it would be an error of the data I think :)

**Comment by tophsic** [comment]
Off course! A better example is:

```edi
TXT+DEL+LOREM ???' IPSUM ??'
```

**Comment by tophsic** [comment]
The tool http://www.edifactviewer.com/ got the same bug.

**Comment by sabas** [comment]
@tophsic here's a fix: replace line 236 with this
```
        $string = preg_replace("/((\?\?)*)'/", "$1§", $string);
        $file=preg_split(self::$DELIMITER."§".self::$DELIMITER."i", $string);
```
Basically when we have the terminator with zero or even numbers of ? (the escape character)
we detect this as the line ending, so we replace it with a safe character (any better ideas than § ? ) and we split segments on that character.

**Comment by tophsic** [comment]
I come back on this issue as I want to get rid of falsy alerts on our apps.

I pushed a new branch `fix-release-character` on my fork, especially tophsic/edifact@e42e2a2 commit to add a failing test (several assertions).

I will get into `Parser` code to see if I fix this. Thanks for you proposition, I will test it.

**Comment by tophsic** [comment]
What is the minimum version of PHP which should be supported?

**Comment by sabas** [comment]
I use PHP 7.1... 
Someone was still using 5.6, but I suggested him to upgrade because for bigger EDI files it becomes too slow.
I would say let's use new features if it simplifies the code.
