### ISSUE TITLE
Question about PRICAT

### ISSUE THREAD

**Issue by seansan** [php-edifact/edifact#66]
Sorry to raise an issue on this. I know it is not the way. 

I have a set of messages in fashion PRICAT, ORDERS, DESADV, ORDRSP etc that I would like to process and parse. Can this also be done with this standard?

For instance, can I process PRICAT messages?
https://www.gs1.org/edi-xml-gs1-eancom/eancom-pricat-s4/syntax-4

If so: how would I read in the data (from file)

thanks - see this as a jump starter to get us started ;P

great that this exists!

**Comment by sabas** [comment]
Hello,
I work with syntax version 3, I never used the version 4... The only difference is the repetition character (*) ?
You can try the Parser and get an array
https://github.com/php-edifact/edifact#ediparser
To process the array you could write a mapping based on GS1 like I did for UN/EDIFACT https://github.com/php-edifact/edifact-mapping
