### ISSUE TITLE
Notice (8): Undefined index: name

### ISSUE THREAD

**Issue by swiffer** [php-edifact/edifact#67]
Reading D06A INVOIC messages shows multiple Notices for undefined indexes:

in edifact 0.2.1:

Notice (8): Undefined index: name [ROOT/vendor/sabas/edifact/src/EDI/Interpreter.php, line 265]

in edifact 0.3.0/dev-master:

Notice (8): Undefined index: name [ROOT/vendor/sabas/edifact/src/EDI/Interpreter.php, line 305]
Notice (8): Undefined index: name [ROOT/vendor/sabas/edifact/src/EDI/Interpreter.php, line 304]
Notice (8): Undefined index: name [ROOT/vendor/sabas/edifact/src/EDI/Interpreter.php, line 307]

**Comment by sabas** [comment]
Could you please send me an example via email?

**Comment by swiffer** [comment]
Done ;)

**Comment by swiffer** [comment]
Fixed in edifact-mapping
