### ISSUE TITLE
Reading and Creating 810/880 Invoice Messages

### ISSUE THREAD

**Issue by cwcrawley** [php-edifact/edifact#68]
I'm trying to understand how the EDI process would work for me to be able to read and also create 810 Invoice Messages, but I'm struggling.

Are there more comprehensive documentation links that I'm missing somewhere to be able to look at?

**Comment by sabas** [comment]
That format is an ANSI EDI transaction I think,
this repository supports UN/EDIFACT (which is the only standard I currently use :-) )

**Comment by cwcrawley** [comment]
That would explain it then! :) Thanks.
