### ISSUE TITLE
Encoding problem / misunderstanding

### ISSUE THREAD

**Issue by ladenise** [php-edifact/edifact#71]
Hello,

First of all, thanks a lot for your hard work. It's great.

I'm having a problem parsing an EDI file. It's encoded as Windows-1252 and UNB is set to UNOC.

Processed by the following code, json_encode returns false.
```
$p = new Parser($fn);
if (count($p->errors()) > 0) {
    echo json_encode($p->errors());
    return;
}
var_dump(json_encode($p->get()));
```

If I convert (using mb_convert_encoding from Windows-1252 to UTF-8), it works.
But UNOC is supposed to be ISO-8859-1 if I'm not mistaken???

Could you help me solve this problem or misunderstanding please?

Thanks in advance.

**Comment by sabas** [comment]
The UNO* specification tells about which characters are allowed (character set), not their encoding...
We had same issue last year, and yes, the best approach would be to decode to utf8
https://github.com/php-edifact/edifact/issues/64#issuecomment-284367823

**Comment by ladenise** [comment]
Ok @sabas, thanks a lot for your help and for the library.
