### ISSUE TITLE
UNA does not container new line character

### ISSUE THREAD

**Issue by hgajjar** [php-edifact/edifact#78]
Hi there,

First of all, thank you so much for this library, its the only one for php and very useful.

However, I'm facing a problem with Encoder that `enableUMA` is adding the UMA line correctly but does not add a new line after it, so the next `UNB` line starts right after `UMA` in the same line.

I think you just need to add a new line here between `$this->symbEnd` and `$this->output`: https://github.com/php-edifact/edifact/blob/master/src/EDI/Encoder.php#L122

**Comment by sabas** [comment]
Only when $wrap = false. This option should be extracted and used into that line...
Would you like to do it?
(An EDI message without newlines is valid)

**Comment by hgajjar** [comment]
Sure, here we go https://github.com/php-edifact/edifact/pull/79 👍

**Comment by sabas** [comment]
Changed a bit (adding it to $symbEnd would cause duplicate newlines) and merged, thanks! :-)

**Comment by hgajjar** [comment]
@sabas would be nice if you can also release it so I can use that in my composer ;)

**Comment by sabas** [comment]
done!
