### ISSUE TITLE
How to create edi document with .edi extension for healthcare

### ISSUE THREAD

**Issue by mpkumar87** [php-edifact/edifact#83]
Hi,

Needs to create edi document with .edi file format for health-care. Also needs to read .edi file. What are procedure to achieve this. What is the standard format for read and write edi files.

Thanks.

**Comment by sabas** [comment]
Hi, you need to check which message standard you need to use first (since you're mentioning healthcare I suspect it would be an ANSI message, and this library isn't for that stardard).
Which message you need to implement?

**Comment by mpkumar87** [comment]
Hi,

I really appreciated your input. Thank you!

We need to process “HIPAA claim payments and premium payments”, so we believe we need to satisfy ASC X12 standard message format and do below transaction set,

Healthcare Claim or Encounter (837)
Claim Payment and Remittance Advice (835)

Please suggest us if anything. 

Thanks in advance!

**Comment by sabas** [comment]
X12 is not supported in my library (never treated them). Here are some links
https://github.com/michaelachrisco/Electronic-Interchange-Github-Resources

**Comment by mpkumar87** [comment]
Thanks for your reply.
