### ISSUE TITLE
File has multiple messages

### ISSUE THREAD

**Issue by erleeman** [php-edifact/edifact#87]
https://github.com/php-edifact/edifact/blob/594112d2f300aa785d90748a9da2813375d1b627/src/EDI/Reader.php#L94

Will that be possible someday? 
For now you have to seperate the messages within a file manually?

Thank you.

**Comment by sabas** [comment]
In Analyser I split them correctly
https://github.com/php-edifact/edifact/blob/master/src/EDI/Interpreter.php#L133

How do you use Reader?

**Comment by erleeman** [comment]
$parser = new Parser($file_content);
$reader = new Reader();
$reader->setParsedFile($this->parser->get());

$reader->readEdiDataValue(['NAD', ['1' => 'SE']], 2, 0);

But for more than 1 message the 'File has multiple messages' error is logged.

**Comment by erleeman** [comment]
OK. Like in #84 
But now, i recognized that preValidate for setParsedFile with extracted groups will return false.

I did not noticed splitMultiMessage. I will have a look. 

Thank you.

**Comment by erleeman** [comment]
Thank you for pointing out splitMulitMessage.

Have a look for testSplitMultiMessage. That figures out how to use it.

https://github.com/php-edifact/edifact/blob/594112d2f300aa785d90748a9da2813375d1b627/tests/EDITest/ReaderTest.php#L78

**Comment by erleeman** [comment]
Seperating the file and loop each message.

https://github.com/php-edifact/edifact/blob/594112d2f300aa785d90748a9da2813375d1b627/tests/EDITest/ReaderTest.php#L78
