### ISSUE TITLE
question marks are not parsed correctly

### ISSUE THREAD

**Issue by lhyx** [php-edifact/edifact#91]
Hi,

Question marks should be added as ?? because it's an escape character.

In this example the question marks escape the ' and this should not happen:

```
ATT+1400+??????'
XRH+3'
```

```
$c = new \EDI\Parser();
$c->setStripRegex('//');
$c->loadString($edistring);
$message       = $c->get();
```
$message contains this:

```
[99] => Array
        (
            [0] => ATT
            [1] => 1400
            [2] => ???'XRH
            [3] => 3
        )
```

As you can see the question marks are correctly parsed into ??? but the ' is still escaped and this is not correct.

Any idea how this could be fixed ?

**Comment by sabas** [comment]
Are you using the latest version? Could you try with some previous tag?

**Comment by tophsic** [comment]
Is this related to !80 and #65 ?

**Comment by lhyx** [comment]
Hi,

I checked both issues before posting. But in the case of 6 question marks the issue still seems to occur. I'm using the latest version 4.0.

**Comment by lhyx** [comment]
Ow I see you released a fix some time ago to solve some of the question mark situations.
So it seems in the case of 6 question marks the problem still occurs for some reason.
