### ISSUE TITLE
Reader cannot be init with a null param

### ISSUE THREAD

**Issue by alexcode** [php-edifact/edifact#97]
Initializing the `Reader` with a parsed array from the `Parser` as noted in the documentation doesn't work as [`Reader::load`](https://github.com/php-edifact/edifact/blob/master/src/EDI/Reader.php#L65) expects a `string` as function parameter.

Is this a bug or is it not supported anymore and the doc should be updated ?
Let me know so I can submit a PR to fix either the doc or the code and related unittest.

```
$c = new Parser($x);

$r = new Reader();
$r->setParsedFile($c->get());
$sender = $r->readEdiDataValue('UNB', 2);
$Dt = $r->readUNBDateTimeOfPreperation();
```
The below code will raise the following error.
`TypeError: Argument 1 passed to EDI/Reader::load() must be of the type string, null given, called in /var/www/vendor/sabas/edifact/src/EDI/Reader.php on line 31`

**Comment by sabas** [comment]
It was typehinted in a past commit, you can remove the string annotation from the load function, so it won't give error anymore....
https://github.com/php-edifact/edifact/commit/aa4f65e7ab699da00f7526995e8c2389ea6b6ded#diff-589fa67850596f880708da58b45e8ac8

**Comment by alexcode** [comment]
Thanks for your answer but should the parser be instantiate if no input is given ? Isn't better to not call `Reader::load` in the `Reader::__construct` when `$url` is `null` ?

**Comment by sabas** [comment]
So putting a condition in the constructor to check for null?
Yeah seems ok!
